# Use the official Node.js base image
FROM node:20-alpine

# Set environment variables to avoid interactive prompts during package installations
ENV DEBIAN_FRONTEND=noninteractive

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files
COPY . . 

# Expose the application port (default Nest.js port is 3000)
EXPOSE 3000

# Start the Nest.js development server
CMD ["npm", "run", "start:dev"]




