FROM python:alpine3.19

# Set environment variables to avoid interactive prompts during package installations
ENV DEBIAN_FRONTEND=noninteractive

# Set the working directory
WORKDIR /scraping

# Install dependencies for running headless Chrome on Alpine
RUN apk update && \
    apk add --no-cache \
    bash \
    curl \
    chromium \
    chromium-chromedriver \
    harfbuzz \
    nss \
    freetype \
    ttf-freefont \
    font-noto \
    libstdc++
    # fonts-noto-cjk \
    
# Install dependencies
COPY requirements.txt ./
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt

# Copy the rest of the application files
COPY . .

# Set up ChromeDriver location for Selenium
ENV CHROME_BIN=/usr/bin/chromium-browser
ENV CHROME_DRIVER=/usr/bin/chromedriver

# Keep container runing for dev 
CMD ["tail", "-f", "/dev/null"]

# Start main script 
# CMD ["python3", "main.py"]
  

