FROM python:alpine3.19

# Set environment variables to avoid interactive prompts during package installations
ENV DEBIAN_FRONTEND=noninteractive

# Set the working directory
WORKDIR /scraping

# Update the package list and install Python and necessary dependencies
# RUN apt-get update && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt ./
RUN pip3 install --break-system-packages -r requirements.txt

# Copy the rest of the application files
COPY . .

# Start main script
CMD ["python3", "main.py"]  

